### ISSUE TITLE
How is this different from a Tokio Night Pro theme?

### ISSUE THREAD

**Issue by nicksp** [marnixkoops/peacock#2]
Hello, thanks for the great themes. I installed both, and run through some of my JS-related files but couldn't see any difference really. How do they differ?

**Comment by marnixkoops** [comment]
Hey Nick, glad you like it. To be honest, they're indeed the same. I felt the theme was so heavily modified from the original that it deserved its own name so I re-uploaded as peacock. Kept the other one online as a bunch of people were already using it ;)!
